import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import TanStackProvider from '@/components/TanStackProvider/TanStackProvider'
import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  modal, // 1. ДОДАЛИ слот модалки як пропс від Next.js
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode // 2. Прописали типи для TypeScript
}>) {
  return (
    <html lang='en' className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <TanStackProvider>
          <Header />
          <main> {children}</main>

          {/* 3. РЕНДЕРИМО модалку всередині провайдера під головним контентом */}
          {modal}

          <Footer />
        </TanStackProvider>
      </body>
    </html>
  )
}
